steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "btcerti"
      - "--image"
      - "gcr.io/$PROJECT_ID/btcerti"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/btcerti"

options:
  logging: CLOUD_LOGGING_ONLY
