steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "btcerti" # Nome do serviço Cloud Run que você quer substituir
      - "--image"
      - "gcr.io/$PROJECT_ID/btcerti" # Imagem Docker criada
      - "--region"
      - "us-central1" # Região do Cloud Run
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # Permite acesso público, retire se quiser acesso autenticado

images:
  - "gcr.io/$PROJECT_ID/btcerti"

options:
  logging: CLOUD_LOGGING_ONLY # Garante logs somente no Cloud Logging para conta customizada
