name: Deploy Voila App to GCP VM

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Todo dia à meia-noite UTC (ajuste se quiser outro horário)
  workflow_dispatch: # Permite disparo manual no GitHub

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Copiar arquivos para a VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          source: "."
          target: "~/BTCERTI"
          strip_components: 1

      - name: Build e Run Docker remoto
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd ~/BTCERTI
            docker stop btcerti || true
            docker rm btcerti || true
            docker build -t btcerti .
            docker run -d --restart unless-stopped --name btcerti -p 80:8866 btcerti

  restart-docker:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Reiniciar container Docker na VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            docker restart btcerti
